export const SLIDES = [
  { title: 'RippleGuard · Team Spectra', points: ['Manipal Hackathon 2026, Cybersecurity track, problem statement P04: Open Source Supply Chains, The Ripple Effect.', 'RippleGuard maps a dependency ecosystem, scores every package with reasons, and simulates how a compromise spreads to production.'] },
  { title: 'The problem', points: ['454,600 new malicious open-source packages in 2025, up 75% year on year, and 99% of them on npm (Sonatype 2026).', 'A supply-chain compromise costs $4.91M on average and takes 267 days to contain (IBM 2025).', 'Scanners score packages one at a time, never show the propagation path, and hide their reasoning.'] },
  { title: 'Our solution', points: ['Map: package-lock.json becomes a full graph with reverse dependents edges.', 'Score: four explainable factors fed by live OSV.dev, EPSS and CVSS 3.1 data.', 'Simulate: time-step ripple from any package to the production root, with what-if quarantine.', 'Explain: every score ships with plain-English reasons.'] },
  { title: 'Risk engine', points: ['Risk combines vulnerability exposure, compromise signal, blast radius, and evidence confidence.', 'On the demo project, qs@6.7.0 scores highest at 0.76 because it is a central junction that reaches the app.', 'The "Why this score?" list is verbatim engine output.'] },
  { title: 'Ripple simulation', points: ['A compromise of qs at 90% reaches express and body-parser at 60.8%, then the app at 45.6%.', 'Baseline blast radius is 60.4%. Blocking express cuts it to 27.1%, a 55.1% reduction.', 'Blocking body-parser only removes 6.3%, because qs still reaches the app through express.'] },
  { title: 'Technical implementation', points: ['Watcher, graph parser, intelligence lookup, risk engine, ripple simulation, REST + SSE API, React dashboard.', '13 of 13 tests pass across engine, simulation and API.', 'No API keys or paid feeds. OSV.dev and FIRST EPSS are free.'] },
  { title: 'Business strategy', points: ['Free CLI drives adoption. Team tier adds history, alerts and a GitHub Action CI gate. Enterprise adds SBOM import, SSO and on-prem.', 'Roadmap: PyPI and Maven in 3 months, CycloneDX SBOM in 6, policy engine in 12.', 'Scan the QR codes for the repo, live dashboard and demo video.'] },
]

export const TEAM = [
  { slug: 'rohit', name: 'Rohit Girish Belagali', role: 'Opening, problem framing & live demo', slides: [1, 2], focus: 'Introduces Team Spectra and RippleGuard, sets up why the dependency tree is now the attack surface, and drives the live dashboard walkthrough.', demo: { to: '/p/demo-project', label: 'Overview' } },
  { slug: 'shashank', name: 'Thambichetty Shashank', role: 'Solution & dependency graph', slides: [3], focus: 'Explains how RippleGuard models the ecosystem as a graph and walks the dependency graph view.', demo: { to: '/p/demo-project/dependencies', label: 'Dependency graph' } },
  { slug: 'harshavardan', name: 'M Harshavardan', role: 'Risk engine & explainability', slides: [4], focus: 'Breaks down the four risk factors and shows the per-package "Why this score?" reasoning.', demo: { to: '/p/demo-project/vulnerabilities', label: 'Vulnerabilities' } },
  { slug: 'tejasvi', name: 'Tejasvi M H', role: 'Ripple simulation & mitigation', slides: [5], focus: 'Runs the qs compromise simulation and compares quarantining express against body-parser.', demo: { to: '/p/demo-project/simulation', label: 'Ripple simulation' } },
  { slug: 'varsha', name: 'Varsha K', role: 'Architecture, feasibility & business', slides: [6, 7], focus: 'Covers the architecture, what is built and tested, the go-to-market plan, and closes with the QR codes.', demo: null },
]
